version: "3.8"

services:
  frontend:
    image: node:20-alpine
    working_dir: /app
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    command: sh -c "npm install && npm run dev"
    networks:
      - banking-web-app-network

  backend:
    image: webdevops/php-nginx:8.2-alpine
    working_dir: /app
    ports:
      - "8000:80"
    volumes:
      - ./backend:/app
    environment:
      WEB_DOCUMENT_ROOT: /app/public
      PHP_DATE_TIMEZONE: Asia/Bangkok
      DB_CONNECTION: mysql
      DB_HOST: database
      DB_PORT: 3306
      DB_DATABASE: banking_web_app_db
      DB_USERNAME: root
      DB_PASSWORD: 2545
    depends_on:
      - database
    networks:
      - banking-web-app-network

  database:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: banking_web_app_db
      MYSQL_ROOT_PASSWORD: 2545
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - banking-web-app-network

networks:
  banking-web-app-network:
    driver: bridge

volumes:
  db_data: